[git]
conventional_commits = false
merge_commits = false

commit_parsers = [
    { message = "^feat(:|\\()", group = "<!-- 0 -->:rocket: New features" },
    { message = "^fix(:|\\()", group = "<!-- 1 -->:bug: Bug fixes" },
    { message = "^perf(:|\\()", group = "<!-- 2 -->:zap: Performance" },
    { message = "^chore(:|\\()", group = "<!-- 3 -->:gear: Miscellaneous" },
    { message = "^docs(:|\\()", group = "<!-- 4 -->:memo: Documentation" },
    { message = "^refactor(:|\\()", group = "<!-- 5 -->:recycle: Refactoring" },
    { message = "^test(:|\\()", group = "<!-- 6 -->:white_check_mark: Tests" },
    { message = "^ci(:|\\()", group = "<!-- 7 -->:construction_worker: CI/CD" },
    { message = "^style(:|\\()", group = "<!-- 8 -->:nail_care: Code Style" },
    { message = "^build(:|\\()", group = "<!-- 9 -->:package: Build System" },
]
commit_preprocessors = [
  # Remove gitmoji, both actual UTF emoji and :emoji:
  { pattern = ' *(:\w+:|[\p{Emoji_Presentation}\p{Extended_Pictographic}](?:\u{FE0F})?\u{200D}?) *', replace = "" },
]

[changelog]
header = "Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    {% if group != "" %}
    ### {{ group | upper_first }}
    {% for commit in commits | unique(attribute="message") %}
        - {{ commit.message | trim | capitalize }}
    {% endfor %}
    {% endif %}
{% endfor %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"
