name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: 🐍 Install python with uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: 📦 Install dependencies
        run: uv pip install --group dev --group gui .

      - name: 🛠️ Build project with uv
        run: uv build

      - name: 🖥️ Run GUI build script
        run: uv run python build-gui-app.py
