name: Pre-Release

on:
  push:
#  pull_request:
#    types: [closed]
  workflow_dispatch:

jobs:
  release:
#    if: |
#      github.event.pull_request.merged == true &&
#      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: 🐍 Install python with uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: 🗂️ Create virtual environment
        run: uv venv

      - name: 📦 Install dependencies
        run: uv pip install --group dev --group gui .

      - name: 🔢 Get current version from project
        id: get_version
        run: |
          source .venv/bin/activate
          echo "CURRENT_VERSION=$(bump-my-version show --current-version)" >> $GITHUB_ENV

      - name: 🔢 Get latest release version
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(gh release view --json tagName -q ".tagName" || echo "none")
          echo "LATEST_RELEASE=${LATEST_RELEASE#v}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🆚 Compare versions
        id: compare
        run: |
          echo "Current version: $CURRENT_VERSION"
          echo "Latest release: $LATEST_RELEASE"

          if [ "$LATEST_RELEASE" = "none" ]; then
            echo "No previous release found. Proceeding to release."
            echo "SHOULD_RELEASE=true" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "$LATEST_RELEASE" "$CURRENT_VERSION" | sort -V | head -n1)" != "$CURRENT_VERSION" ]; then
            echo "Current version is newer than latest release."
            echo "SHOULD_RELEASE=true" >> $GITHUB_ENV
          else
            echo "Current version is NOT newer. Skipping release."
            echo "SHOULD_RELEASE=false" >> $GITHUB_ENV
          fi
        env:
          CURRENT_VERSION: ${{ env.CURRENT_VERSION }}
          LATEST_RELEASE: ${{ env.LATEST_RELEASE }}

      - name: 🛠️ Build project with uv
        if: env.SHOULD_RELEASE == 'true'
        run: uv build

      - name: 🖥️ Run GUI build script
        if: env.SHOULD_RELEASE == 'true'
        run: uv run python build-gui-app.py

      - name: 🚀 Create prerelease with build artifacts
        if: env.SHOULD_RELEASE == 'true'
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af
        with:
          tag: "v${{ env.CURRENT_VERSION }}"
          name: "Pre-release v${{ env.CURRENT_VERSION }} for PR #${{ github.event.pull_request.number }}"
          body: |
            Automatic pre-release for PR #${{ github.event.pull_request.number }}.
          prerelease: true
          artifacts: |
            dist/*.zip
            dist/*.tar.gz
            dist/*.whl
